### ISSUE TITLE
/PointCloudImage和/camera_pointcloud没有发布消息

### ISSUE THREAD

**Issue by Vansenyann** [LeisureLei/lidar_cam_calibration#1]
按照readme里的说明，修改了相关话题名，但以上两个话题无法发布消息

**Comment by LeisureLei** [comment]
> 按照readme里的说明，修改了相关话题名，但以上两个话题无法发布消息

launch文件里把话题做了映射，remap from A to B，修改B即可。另外这些话题都是订阅的话题，“/cam00/image_raw"是订阅的图像话题；"/velodyne_points"是订阅的点云话题。
这个代码使用的是kitti数据集的数据进行测试的，因此lidar点云到相机图像的投影是依据kitti官方给的方式，使用其他的数据进行测试时，需要修改server.cpp的对应代码。
如果参数都正确进行设置的话，/camrea_pointcloud和/PointCloudImg应该是发布消息的，建议先确认topic是否正确订阅了，还不行就在代码里逐行打印信息，调试一下。

**Comment by Vansenyann** [comment]
launch 文件都确实都修改了，R_rect_00和P_rect_00是相机修正矩阵吗？可以分享一下kitti的.avi文件吗？
